spring:
  config:
    activate:
      on-profile: local
    import:
      - core-local.yml
      - api-local.yml
      - client-repository-local.yml
      - rabbitmq-local.yml
      - postgresql-local.yml
      - redis-local.yml
      - clickhouse-local.yml

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - core-dev.yml
      - api-dev.yml
      - client-repository-dev.yml
      - rabbitmq-dev.yml
      - postgresql-dev.yml
      - redis-dev.yml
      - clickhouse-dev.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - core-prod.yml
      - api-prod.yml
      - client-repository-prod.yml
      - rabbitmq-prod.yml
      - postgresql-prod.yml
      - redis-prod.yml
      - clickhouse-prod.yml
